apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: msusers-ns
spec:
  selector:
    app: java-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080