apiVersion: v1
kind: Secret
metadata:
  name: postgre-cred
  namespace: msusers-ns
type: Opaque
data:
  username: {{ .Values.dbSecret.username }}
  password: {{ .Values.dbSecret.password }}
  dbname: {{ .Values.dbSecret.dbname }}