apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre-configmap
  namespace: msusers-ns
data:
  init.sql: |
    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET transaction_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;
    DROP DATABASE IF EXISTS users_db;
    CREATE DATABASE users_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';
    ALTER DATABASE users_db OWNER TO root;
    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET transaction_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;
    SET default_tablespace = '';
    SET default_table_access_method = heap;
    CREATE TABLE public.users (
        id integer NOT NULL,
        username character varying(200) NOT NULL,
        first_name character varying(200) NOT NULL,
        last_name character varying(200) NOT NULL,
        email character varying(254) NOT NULL,
        phone character varying(20) NOT NULL
    );
    CREATE SEQUENCE public.users_id_seq
        START WITH 1001
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;
    ALTER SEQUENCE public.users_id_seq OWNER TO root;
    COPY public.users (id, username, first_name, last_name, email, phone) FROM stdin;
    1	vasya	Vassily	Petrov	vpetrov@jr.com	+7 (191) 322-22-33)
    2	petya	Pjotr	Vasechkin	pvasechkin@jr.com	+7 (191) 223-33-22)
    3	masha	Mariya	Startseva	mstartseva@jr.com	+7 (191) 323-23-32)
    1001	user01	Ivan	Ivanov	ivanov@example.com	11111
    1002	user01	Ivan	Ivanov	ivanov@example.com	11111
    \.
    SELECT pg_catalog.setval('public.users_id_seq', 1002, true);
    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_pkey PRIMARY KEY (id);