apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: msusers-ns
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: 'postgres:17'
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-cred
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgre-cred
              key: dbname
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP      
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"